#!/bin/bash

set -e

# This script is run through `pixi run -e <env> ...`, so the environment is
# already activated. We uninstall pytest (and the legacy `py` package) to check
# that scikit-learn's test utilities can still be imported when pytest is not
# available (pytest is a soft dependency for end users).
pip uninstall -y py pytest

if [[ "$COVERAGE" == "true" ]]; then
    # conda may remove coverage when uninstall pytest and py
    pip install coverage
    # Need to append the coverage to the existing .coverage generated by
    # running the tests. Make sure to reuse the same coverage
    # configuration as the one used by the main pytest run to be
    # able to combine the results.
    CMD="coverage run --rcfile=$PWD/.coveragerc"
else
    CMD="python"
fi

# .coverage from running the tests is in TEST_DIR
pushd $TEST_DIR
$CMD -m sklearn.utils.tests.test_estimator_checks
popd
