comment: false

coverage:
  status:
    project:
      default:
        # Commits pushed to main should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%
    patch:
      default:
        # Be tolerant on slight code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        # Note: The coverage stats are still uploaded
        # to codecov so that PR reviewers can see uncovered lines
        target: auto
        threshold: 1%

codecov:
  notify:
    # Prevent codecov from calculating the coverage results before all expected uploads
    # are in. This value is set to the total number of jobs uploading coverage reports.
    after_n_builds: 7

ignore:
- "sklearn/externals"
- "sklearn/_build_utils"
- "sklearn/__check_build"
- "sklearn/_min_dependencies.py"
- "**/conftest.py"
