[build-system]
requires = [
    "meson-python>=0.17.1",
    "cython>=3.1.2",
    "numpy>=2.0",
    "scipy>=1.10.0"
]
build-backend = "mesonpy"

[project]
name = "scikit-learn"
description = "Machine learning in Python"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "BSD-3-Clause"}

authors = [
    {name = "scikit-learn developers", email = "scikit-learn@python.org"}
]

dependencies = [
    "numpy>=1.24.1",
    "scipy>=1.10.0",
    "joblib>=1.3.0",
    "threadpoolctl>=3.2.0"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://scikit-learn.org"
Source = "https://github.com/scikit-learn/scikit-learn"
Issues = "https://github.com/scikit-learn/scikit-learn/issues"

[project.optional-dependencies]

dev = [
    "pytest>=7.1.2",
    "pytest-cov>=2.9.0",
    "ruff>=0.12.2",
    "mypy>=1.15"
]

docs = [
    "sphinx>=7.3.7",
    "pydata-sphinx-theme>=0.15.3",
    "numpydoc>=1.2.0",
    "matplotlib>=3.6.1",
    "pandas>=1.5.0"
]

examples = [
    "matplotlib>=3.6.1",
    "pandas>=1.5.0",
    "seaborn>=0.13.0"
]
