"""
This script generates an html table of contributors, with names and avatars.
The list is generated from scikit-learn's teams on GitHub, plus a small number
of hard-coded contributors.

The table should be updated for each new inclusion in the teams.
Generating the table requires admin rights.
"""

import getpass
import sys
import time
from os import path
from pathlib import Path

import requests

print("Input user:", file=sys.stderr)
user = input()
token = getpass.getpass("Input access token:\n")
auth = (user, token)

LOGO_URL = "https://avatars2.githubusercontent.com/u/365630?v=4"
REPO_FOLDER = Path(path.abspath(__file__)).parent.parent
API_ENTRY_POINT = "https://api.github.com/orgs/scikit-learn/"
RATE_LIMIT_RETRY_DELAYS = (10, 30, 0)  # seconds

# GitHub API returns 30 items per page.
TEAM_PAGES = 2
MEMBER_PAGES = 3

TEAM_SLUGS = {
    "core_devs": "core-devs",
    "contributor_experience_team": "contributor-experience-team",
    "comm_team": "communication-team",
    "documentation_team": "documentation-team",
}

# Missing/incorrect names as reported by the GitHub API.
MISSING_NAMES = {
    "bthirion": "Bertrand Thirion",
    "dubourg": "Vincent Dubourg",
    "Duchesnay": "Edouard Duchesnay",
    "Lars": "Lars Buitinck",
    "MechCoder": "Manoj Kumar",
}

session = requests.Session()
session.auth = auth


def get(url):
    reply = None
    for sleep_time in RATE_LIMIT_RETRY_DELAYS:
        reply = session.get(url)
        api_limit = (
            "message" in reply.json()
            and "API rate limit exceeded" in reply.json()["message"]
        )
        if not api_limit:
            break
        print("API rate limit exceeded, waiting..")
        time.sleep(sleep_time)

    reply.raise_for_status()
    return reply


def get_paginated_logins(url, n_pages):
    """Fetch `n_pages` pages (30 entries each) of logins from a GitHub API endpoint."""
    entries = []
    for page in range(1, n_pages + 1):
        reply = get(f"{url}?page={page}")
        entries.extend(reply.json())
    return {entry["login"] for entry in entries}


def get_contributors():
    """Get the list of contributor profiles. Require admin rights."""
    teams = {}
    for name, slug in TEAM_SLUGS.items():
        print(f"Retrieving {slug}\n")
        teams[name] = get_paginated_logins(f"{API_ENTRY_POINT}teams/{slug}/members", TEAM_PAGES)

    core_devs = teams["core_devs"]
    contributor_experience_team = teams["contributor_experience_team"]
    comm_team = teams["comm_team"]
    documentation_team = teams["documentation_team"]

    # get members of scikit-learn on GitHub
    print("Retrieving members\n")
    members = get_paginated_logins(f"{API_ENTRY_POINT}members", MEMBER_PAGES)

    # add missing contributors with GitHub accounts
    members |= {"dubourg", "mbrucher", "thouis", "jarrodmillman"}
    # add missing contributors without GitHub accounts
    members |= {"Angel Soler Gollonet"}
    # remove CI bots
    members -= {"sklearn-ci", "sklearn-wheels", "sklearn-lgtm"}
    contributor_experience_team -= (
        core_devs  # remove ogrisel from contributor_experience_team
    )

    emeritus = (
        members
        - core_devs
        - contributor_experience_team
        - comm_team
        - documentation_team
    )

    # hard coded
    emeritus_contributor_experience_team = {
        "cmarmo",
    }
    emeritus_comm_team = {"reshamas", "laurburke"}

    # Up-to-now, we can subtract the team emeritus from the original emeritus
    emeritus -= emeritus_contributor_experience_team | emeritus_comm_team

    def profiles(logins):
        """Fetch profiles for a set of logins, sorted by last name."""
        return sorted((get_profile(login) for login in logins), key=key)

    return (
        profiles(core_devs),
        profiles(emeritus),
        profiles(contributor_experience_team),
        profiles(emeritus_contributor_experience_team),
        profiles(comm_team),
        profiles(emeritus_comm_team),
        profiles(documentation_team),
    )


def get_profile(login):
    """Get the GitHub profile from login"""
    print(f"get profile for {login}")
    try:
        profile = get(f"https://api.github.com/users/{login}").json()
    except requests.exceptions.HTTPError:
        return dict(name=login, avatar_url=LOGO_URL, html_url="")

    if profile["name"] is None:
        profile["name"] = profile["login"]

    # fix missing names
    if profile["name"] in MISSING_NAMES:
        profile["name"] = MISSING_NAMES[profile["name"]]

    return profile


def key(profile):
    """Get a sorting key based on the lower case last name, then firstname"""
    components = profile["name"].lower().split(" ")
    return " ".join([components[-1]] + components[:-1])


def generate_table(contributors):
    lines = [
        ".. raw :: html\n",
        "    <!-- Generated by generate_authors_table.py -->",
        '    <div class="sk-authors-container">',
        "    <style>",
        "      img.avatar {border-radius: 10px;}",
        "    </style>",
    ]
    for contributor in contributors:
        lines.append("    <div>")
        lines.append(
            "    <a href='{}'><img src='{}' class='avatar' /></a> <br />".format(
                contributor["html_url"], contributor["avatar_url"]
            )
        )
        lines.append(f"    <p>{contributor['name']}</p>")
        lines.append("    </div>")
    lines.append("    </div>")
    return "\n".join(lines) + "\n"


def generate_list(contributors):
    lines = [f"- {contributor['name']}" for contributor in contributors]
    return "\n".join(lines) + "\n"


def write_rst(filename, content):
    with open(REPO_FOLDER / "doc" / filename, "w+", encoding="utf-8") as rst_file:
        rst_file.write(content)


if __name__ == "__main__":
    (
        core_devs,
        emeritus,
        contributor_experience_team,
        emeritus_contributor_experience_team,
        comm_team,
        emeritus_comm_team,
        documentation_team,
    ) = get_contributors()

    print("Generating rst files")

    # (contributors, output filename, table-vs-list generator)
    outputs = [
        (core_devs, "maintainers.rst", generate_table),
        (emeritus, "maintainers_emeritus.rst", generate_list),
        (
            contributor_experience_team,
            "contributor_experience_team.rst",
            generate_table,
        ),
        (
            emeritus_contributor_experience_team,
            "contributor_experience_team_emeritus.rst",
            generate_list,
        ),
        (comm_team, "communication_team.rst", generate_table),
        (emeritus_comm_team, "communication_team_emeritus.rst", generate_list),
        (documentation_team, "documentation_team.rst", generate_table),
    ]

    for contributors, filename, generator in outputs:
        write_rst(filename, generator(contributors))
