parameters:
  name: ''
  vmImage: ''


jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    TEST_DIR: "/tmp/sklearn"
    VIRTUALENV_DIR: "testvenv"
    CHECK_PYTEST_SOFT_DEPENDENCY: false
  strategy:
    matrix:
      ${{ if eq(parameters.name, 'Linux') }}:
        py35_np_111:
          DISTRIB: "ubuntu"
          PYTHON_VERSION: "3.5"
          NUMPY_VERSION: "1.11.0"
          SCIPY_VERSION: "0.17.0"
          PILLOW_VERSION: "4.0.0"
          SKLEARN_SITE_JOBLIB: "1"
          JOBLIB_VERSION: "0.11"

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.5'
        architecture: 'x64'
    - script: |
        build_tools/azure/install.sh
      displayName: 'Install'
    - script: |
        build_tools/azure/test_script.sh
      displayName: 'Test library'
    - script: |
        build_tools/azure/test_docs.sh
      displayName: 'Test docs'
    - script: |
        build_tools/azure/test_pytest_soft_dependency.sh
      displayName: 'Test soft dependency'
