parameters:
  name: ''
  vmImage: ''
  matrix: []
  dependsOn: []
  dependsOnParallel: []
  condition: ''
  commitMessage: ''

jobs:
# When [azure all-parallel] is *not* in the commit message, this build is enabled.
# Later builds should check if this job succeed or skipped by using:
# in(dependencies[{{ parameters.name }}]['result'], 'Succeeded', 'Skipped')
- template: posix.yml
  parameters:
    name: ${{ parameters.name }}
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: |
      and(
        ${{ parameters.condition }},
        not(contains(${{ parameters.commitMessage }}, '[azure all-parallel]'))
      )

# This configures the "parallel" build. The build on top is skipped so
# later builds can run in parallel with this "parallel" configuration.
# When [azure all-parallel] is in the commit message, this build is enabled.
- template: posix.yml
  parameters:
    name: ${{ parameters.name }}_Parallel
    vmImage: ${{ parameters.vmImage }}
    matrix: ${{ parameters.matrix }}
    dependsOn: ${{ parameters.dependsOnParallel }}
    condition: |
      and(
        ${{ parameters.condition }},
        contains(${{ parameters.commitMessage }}, '[azure all-parallel]')
      )
