#!/bin/bash

set -e

# CHECK_PYTEST_SOFT_DEPENDENCY only true with conda
if [[ "$CHECK_PYTEST_SOFT_DEPENDENCY" == "true" ]]; then
    export PATH=$HOME/miniconda3/bin:$PATH
    source activate $VIRTUALENV
    conda remove -y py pytest || pip uninstall -y py pytest

    if [[ "$COVERAGE" == "true" ]]; then
        # Need to append the coverage to the existing .coverage generated by
        # running the tests
        CMD="coverage run --append"
    else
        CMD="python"
    fi

    # .coverage from running the tests is in TEST_DIR
    pushd $TEST_DIR
    $CMD -m sklearn.utils.tests.test_estimator_checks
    popd
fi
