from __future__ import print_function

import sys
import requests
import getpass

try:
    # With authentication: up to 5000 requests per hour.
    print("user:", file=sys.stderr)
    user = input()
    passwd = getpass.getpass()
    auth = (user, passwd)
except IndexError:
    # Without authentication: up to 60 requests per hour.
    auth = None

ROW_SIZE = 7
LOGO_URL = 'https://avatars2.githubusercontent.com/u/365630?v=4'


def group(it, size):
    """Group iterable into lines"""
    gr = []
    for ele in it:
        gr.append(ele)
        if len(gr) == size:
            yield gr
            gr = []
    if len(gr) != 0:
        yield gr


def get_contributors():
    """Get the list of contributor profiles. Require the push rights."""
    # get members of scikit-learn teams on github
    members = []
    for team in [11523, 33471]:
        for page in [1, 2]:  # 30 per page
            members.extend(requests.get(
                "https://api.github.com/teams/%d/members?page=%d"
                % (team, page), auth=auth).json())

    # keep only the logins
    logins = [c['login'] for c in members]
    # add missing contributors with github accounts
    logins.extend(['dubourg', 'jarrodmillman', 'mbrucher', 'thouis'])
    # add missing contributors without github accounts
    logins.extend(['Angel Soler Gollonet'])
    # remove duplicate
    logins = set(logins)
    # remove CI
    logins.remove('sklearn-ci')

    # get profiles from github
    profiles = [get_profile(login) for login in logins]
    # sort by first name
    profiles = sorted(profiles, key=key)

    return profiles


def get_profile(login):
    """Get the GitHub profile from login"""
    profile = requests.get("https://api.github.com/users/%s" % login,
                           auth=auth).json()
    if 'name' not in profile:
        # default if the login does not exist
        return dict(name=login, avatar_url=LOGO_URL, html_url="")
    else:
        if profile["name"] is None:
            profile["name"] = profile["login"]
        return profile


def key(profile):
    """Get the last name in lower case"""
    return profile["name"].lower().split(' ')[-1]


contributors = get_contributors()

print(".. raw :: html\n")
print("    <!-- Generated by gen_authors.py -->")
print("    <table>")
print("    <col style='width:%d%%' span='%d'>"
      % (int(100 / ROW_SIZE), ROW_SIZE))
print("    <style>")
print("      img.avatar {border-radius: 10px;}")
print("      td {vertical-align: top;}")
print("    </style>")
for row in group(contributors, size=ROW_SIZE):
    print("    <tr>")
    for contributor in row:
        print("    <td>")
        print("    <a href='%s'><img src='%s' class='avatar' /></a> <br />"
              % (contributor["html_url"], contributor["avatar_url"]))
        print("    <p>%s</p>" % contributor["name"])
        print("    </td>")
    print("    </tr>")
print("    </table>")
