"""
=======================================================
Scalable learning with polynomial kernel aproximation
=======================================================

This example illustrates the use of :class:`PolynomialSampler` to efficiently
generate polynomial kernel feature-space approximations. This is used
to train linear classifiers that approximate the accuracy of kernelized ones.

.. currentmodule:: sklearn.kernel_approximation

We use the Covtype dataset [2]_, trying to reproduce the experiments on the
original paper of Tensor Sketch [1]_, i.e. the algorithm implemented by
:class:`PolynomialSampler`.

First, we compute the accuracy of a linear classifier on the original
features. Then, we train linear classifiers on different numbers of
features (`n_components`) generated by :class:`PolynomialSampler`,
approximating the accuracy of a kernelized classifier in a scalable manner.
"""
print(__doc__)

# Author: Daniel Lopez-Sanchez <lope@usal.es>
# License: BSD 3 clause
from sklearn.datasets import fetch_covtype
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize, MinMaxScaler
from sklearn.svm import LinearSVC
from sklearn.kernel_approximation import PolynomialSampler
from sklearn.pipeline import Pipeline

##############################################################################
# Load the Covtype dataset, which contains 581,012 samples
# with 54 features each, distributed among 6 classes. The goal of this dataset
# is to predict forest cover type from cartographic variables only
# (no remotely sensed data). After loading, we transform it into a binary
# classification problem to match the version of the dataset in the
# LIBSVM webpage [2]_, which was the one used in [1]_.

data = fetch_covtype()
X, y = data["data"], data["target"]

y[y != 2] = 0
y[y == 2] = 1  # We will try to separate class 2 from the other 6 classes.

##############################################################################
# Here we select 20,000 samples for training and 20,000 for testing.
# To actually reproduce the results in the original Tensor Sketch paper,
# select 100,000.

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=20_000,
                                                    test_size=20000,
                                                    random_state=42)

##############################################################################
# Now scale features to the range [0, 1] to match the format of the dataset in
# the LIBSVM webpage, and then normalize to unit length as done in the
# original Tensor Sketch paper [1].

mm = MinMaxScaler().fit(X_train)
X_train = normalize(mm.transform(X_train))
X_test = normalize(mm.transform(X_test))

##############################################################################
# As a baseline, train a linear SVM on the original features and print the
# accuracy:

lsvm = LinearSVC()
lsvm.fit(X_train, y_train)
lsvm_score = 100*lsvm.score(X_test, y_test)
print(f"Linear SVM score on raw features: {lsvm_score:.2f} %%")

##############################################################################
# Then we train linear SVMs on the features generated by
# :class:`PolynomialSampler` with different values for `n_components`, showing
# that these kernel feature approximations improve the accuracy of linear
# classification:

for n_components in [200, 500, 1000, 1500]:

    pipeline = Pipeline(steps=[("kernel_approximator",
                                PolynomialSampler(
                                    n_components=n_components,
                                    degree=4)),
                               ("linear_classifier", LinearSVC())])
    pipeline.fit(X_train, y_train)
    ps_lsvm_score = 100 * pipeline.score(X_test, y_test)

    print(f"Linear SVM score on {n_components} PolynomialSampler " +
          f"features: {ps_lsvm_score:.2f} %%")

##############################################################################
# Finally, train a kernelized SVM to see how well :class:`PolynomialSampler`
# is approximating the performance of the kernel. This of course may take some
# time, as the SVC class has a relatively poor scalability. This is the
# reason why kernel approximators are so useful:

from sklearn.svm import SVC
ksvm = SVC(C=500., kernel="poly", degree=4, coef0=0,
           gamma=1.).fit(X_train, y_train)
ksvm_score = 100*ksvm.score(X_test, y_test)
print(f"Kernel-SVM score on raw featrues: {ksvm_score:.2f} %%")

##############################################################################
# As we can see, this kernelized SVM achieves a slightly higher accuracy, but
# training is nearly five times slower in this case.

##############################################################################
# References
# ==========
#
# [1] Pham, N., & Pagh, R. (2013, August). Fast and scalable polynomial
# kernels via explicit feature maps. In Proceedings of the 19th ACM SIGKDD
# international conference on Knowledge discovery and data mining (pp. 239-247)
# (https://chbrown.github.io/kdd-2013-usb/kdd/p239.pdf)
#
# [2] LIBSVM binary datasets repository
# (https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html)
