# This list of English stop words is taken from the "Glasgow Information
# Retrieval Group". The original list can be found at
# http://ir.dcs.gla.ac.uk/resources/linguistic_utils/stop_words
ENGLISH_STOP_WORDS = frozenset([
    "a", "about", "above", "across", "after", "afterwards", "again", "against",
    "all", "almost", "alone", "along", "already", "also", "although", "always",
    "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
    "any", "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
    "around", "as", "at", "back", "be", "became", "because", "become",
    "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
    "below", "beside", "besides", "between", "beyond", "bill", "both",
    "bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con",
    "could", "couldnt", "cry", "de", "describe", "detail", "do", "done",
    "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
    "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
    "everything", "everywhere", "except", "few", "fifteen", "fifty", "fill",
    "find", "fire", "first", "five", "for", "former", "formerly", "forty",
    "found", "four", "from", "front", "full", "further", "get", "give", "go",
    "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter",
    "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
    "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
    "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
    "latterly", "least", "less", "ltd", "made", "many", "may", "me",
    "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly",
    "move", "much", "must", "my", "myself", "name", "namely", "neither",
    "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
    "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
    "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
    "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
    "please", "put", "rather", "re", "same", "see", "seem", "seemed",
    "seeming", "seems", "serious", "several", "she", "should", "show", "side",
    "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
    "something", "sometime", "sometimes", "somewhere", "still", "such",
    "system", "take", "ten", "than", "that", "the", "their", "them",
    "themselves", "then", "thence", "there", "thereafter", "thereby",
    "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
    "third", "this", "those", "though", "three", "through", "throughout",
    "thru", "thus", "to", "together", "too", "top", "toward", "towards",
    "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
    "very", "via", "was", "we", "well", "were", "what", "whatever", "when",
    "whence", "whenever", "where", "whereafter", "whereas", "whereby",
    "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
    "who", "whoever", "whole", "whom", "whose", "why", "will", "with",
    "within", "without", "would", "yet", "you", "your", "yours", "yourself",
    "yourselves"])

TURKİSH_STOP_WORDS = frozenset([
	"ama",
	"amma",
	"anca",
	"ancak",
	"belki",
	"çünkü",
	"dahi",
	"eğer",
	"emme",
	"fakat",
	"gah",
	"gerek",
	"hakeza",
	"halbuki",
	"hatta",
	"hele",
	"hem",
	"hoş",
	"ile",
	"ile",
	"imdi",
	"ister",
	"kah",
	"keşke",
	"keza",
	"kezalik",
	"kim",
	"lakin",
	"madem",
	"mademki",
	"mamafih",
	"meğer",
	"meğerki",
	"meğerse",
	"netekim",
	"neyse",
	"nitekim",
	"oysa",
	"oysaki",
	"şayet",
	"velev",
	"velhasıl",
	"velhasılıkelam",
	"veya",
	"veyahut",
	"yahut",
	"yalnız",
	"yani",
	"yok",
	"yoksa",
	"zira",
	"acaba",
	"acep",
	"açıkça",
	"açıkçası",
	"adamakıllı",
	"adeta",
	"bazen",
	"bazı",
	"bilcümle",
	"binaen",
	"binaenaleyh",
	"bir",
	"biraz",
	"birazdan",
	"birden",
	"birden",
	"birdenbire",
	"birice",
	"birlikte",
	"bitevi",
	"biteviye",
	"bittabi",
	"bizatihi",
	"bizce",
	"bizcileyin",
	"bizden",
	"bizzat",
	"boşuna",
	"böyle",
	"böylece",
	"böylecene",
	"böylelikle",
	"böylemesine",
	"böylesine",
	"buracıkta",
	"burada",
	"buradan",
	"büsbütün",
	"çabuk",
	"çabukça",
	"çeşitli",
	"çoğu",
	"çoğun",
	"çoğunca",
	"çoğunlukla",
	"çok",
	"çokça",
	"çokluk",
	"çoklukla",
	"cuk",
	"daha",
	"dahil",
	"dahilen",
	"daima",
	"demin",
	"demincek",
	"deminden",
	"derakap",
	"derhal",
	"derken",
	"diye",
	"elbet",
	"elbette",
	"enikonu",
	"epey",
	"epeyce",
	"epeyi",
	"esasen",
	"esnasında",
	"etraflı",
	"etraflıca",
	"evleviyetle",
	"evvel",
	"evvela",
	"evvelce",
	"evvelden",
	"evvelemirde",
	"evveli",
	"gayet",
	"gayetle",
	"gayri",
	"gayrı",
	"geçende",
	"geçenlerde",
	"gene",
	"gerçi",
	"gibi",
	"gibilerden",
	"gibisinden",
	"gine",
	"halen",
	"halihazırda",
	"haliyle",
	"handiyse",
	"hani",
	"hasılı",
	"hulasaten",
	"iken",
	"illa",
	"illaki",
	"itibarıyla",
	"iyice",
	"iyicene",
	"kala",
	"kez",
	"kısaca",
	"külliyen",
	"lütfen",
	"nasıl",
	"nasılsa",
	"nazaran",
	"neden",
	"nedeniyle",
	"nedense",
	"nerde",
	"nerden",
	"nerdeyse",
	"nerede",
	"nereden",
	"neredeyse",
	"nereye",
	"neye",
	"neyi",
	"nice",
	"niçin",
	"nihayet",
	"nihayetinde",
	"niye",
	"oldu",
	"oldukça",
	"olur",
	"onca",
	"önce",
	"önceden",
	"önceleri",
	"öncelikle",
	"onculayın",
	"ondan",
	"oracık",
	"oracıkta",
	"orada",
	"oradan",
	"oranca",
	"oranla",
	"oraya",
	"öyle",
	"öylece",
	"öylelikle",
	"öylemesine",
	"pek",
	"pekala",
	"pekçe",
	"peki",
	"peyderpey",
	"sadece",
	"sahi",
	"sahiden",
	"sanki",
	"sonra",
	"sonradan",
	"sonraları",
	"sonunda",
	"şöyle",
	"şuncacık",
	"şuracıkta",
	"tabii",
	"tam",
	"tamam",
	"tamamen",
	"tamamıyla",
	"tek",
	"vasıtasıyla",
	"yakinen",
	"yakında",
	"yakından",
	"yakınlarda",
	"yalnız",
	"yalnızca",
	"yeniden",
	"yenilerde",
	"yine",
	"yok",
	"yoluyla",
	"yüzünden",
	"zaten",
	"zati",
	"ait",
	"bari",
	"beri",
	"bile",
	"değin",
	"dek",
	"denli",
	"doğru",
	"dolayı",
	"dolayısıyla",
	"gelgelelim",
	"gibi",
	"gırla",
	"göre",
	"hasebiyle",
	"için",
	"ila",
	"ile",
	"ilen",
	"indinde",
	"inen",
	"kadar",
	"kaffesi",
	"karşın",
	"kelli",
	"Leh",
	"maada",
	"mebni",
	"naşi",
	"rağmen",
	"üzere",
	"zarfında",
	"öbür",
	"bana",
	"başkası",
	"ben",
	"beriki",
	"birbiri",
	"birçoğu",
	"biri",
	"birileri",
	"birisi",
	"birkaçı",
	"biz",
	"bizimki",
	"buna",
	"bunda",
	"bundan",
	"bunlar",
	"bunu",
	"bunun",
	"burası",
	"çoğu",
	"çoğu",
	"çokları",
	"çoklarınca",
	"cümlesi",
	"değil",
	"diğeri",
	"filanca",
	"hangisi",
	"hepsi",
	"hiçbiri",
	"iş",
	"kaçı",
	"kaynak",
	"kendi",
	"kim",
	"kimi",
	"kimisi",
	"kimse",
	"kimse",
	"kimsecik",
	"kimsecikler",
	"nere",
	"neresi",
	"öbürkü",
	"öbürü",
	"ona",
	"onda",
	"ondan",
	"onlar",
	"onu",
	"onun",
	"öteki",
	"ötekisi",
	"öz",
	"sana",
	"sen",
	"siz",
	"şuna",
	"şunda",
	"şundan",
	"şunlar",
	"şunu",
	"şunun",
	"şura",
	"şuracık",
	"şurası"])
