name: Close PR if linked issue is not ready

permissions:
  contents: read
  issues: read
  pull-requests: write

on:
  pull_request_target:
    types:
      - opened

jobs:
  close-pr-if-issue-not-ready:
    name: Check linked issue readiness
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install PyGithub
        run: pip install -Uq PyGithub
      - name: Checkout workflow script
        uses: actions/checkout@v7
        with:
          sparse-checkout: .github/scripts/close-pr-if-issue-not-ready.py
          sparse-checkout-cone-mode: false # false for files/ true for directories
      - name: Check linked issue readiness
        run: python .github/scripts/close-pr-if-issue-not-ready.py
