name: Welcome first-time contributor
# Post a welcome comment when a first-time contributor opens a pull request.

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types:
      - opened

jobs:

  post_comment:
    name: welcome
    if: |
      github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' ||
      github.event.pull_request.author_association == 'FIRST_TIMER' ||
      github.event.pull_request.author_association == 'NONE'
    runs-on: ubuntu-latest

    steps:

      - name: Post welcome comment
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$GH_REPO/issues/$PULL_REQUEST_NUMBER/comments \
          -f "body=$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          BODY: |
            Thank you for opening your first pull request to scikit-learn! 🎉


            To help get your contribution reviewed, please make sure that:

            - You have filled out the [pull request template](https://github.com/scikit-learn/scikit-learn/blob/main/.github/PULL_REQUEST_TEMPLATE.md).
            - The pull request addresses an existing issue that is ready for
              contribution (e.g. not tagged as "Needs Triage", "Needs Decision", ...).
              If you are proposing a new feature, please open an issue to discuss it first.
            - There are no other open pull requests already targeting the same issue.
            - You have followed the [pull request checklist](https://scikit-learn.org/stable/developers/contributing.html#pull-request-checklist).
              In particular, linting and tests should pass.
